<?php

namespace App\Http\Controllers;

use Carbon\Carbon;
use Illuminate\Support\Facades\Cookie;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Http;
use Symfony\Component\DomCrawler\Crawler;

class JadwalSholatController extends Controller
{
    public function getJadwalShalat(Request $request) {
        // Ambil locationId dari query atau cookie
        $locationId = $request->query('locationId', $request->cookie('selectedLocation'));

        // Ambil semua lokasi
        $locations = $this->getLocations();

        // Simpan locationId ke dalam cookie jika ada
        if ($locationId) {
            Cookie::queue('selectedLocation', $locationId, 60 * 24); // Simpan 1 hari
        }

        $selectedLocationName = $locations[$locationId] ?? 'Pilih Lokasi';

        // Fetch jadwal berdasarkan locationId
        if ($locationId) {
            $response = Http::get("https://jadwalsholat.org/adzan/ajax/next/ajax.daily.php?id={$locationId}");
            $data = $response->json();

            $jadwal = [
                'shubuh' => $data['schedules']['shubuh'] ?? 'N/A',
                'dzuhur' => $data['schedules']['dzuhur'] ?? 'N/A',
                'ashar'  => $data['schedules']['ashr'] ?? 'N/A',
                'maghrib'=> $data['schedules']['maghrib'] ?? 'N/A',
                'isya'   => $data['schedules']['isya'] ?? 'N/A',
            ];
        } else {
            $jadwal = [
                'shubuh' => 'N/A',
                'dzuhur' => 'N/A',
                'ashar'  => 'N/A',
                'maghrib'=> 'N/A',
                'isya'   => 'N/A',
            ];
        }

        $currentTime = Carbon::now();

        $nextPrayer = null;
        $timeToNextPrayer = null;

        foreach ($jadwal as $prayer => $time) {
            if ($time !== 'N/A') {  // Pastikan waktu valid
                $prayerTime = Carbon::parse($time);

                // Jika waktu sholat lebih besar dari waktu saat ini
                if ($prayerTime->isFuture()) {
                    $nextPrayer = $prayer;
                    $timeToNextPrayer = $currentTime->diffInSeconds($prayerTime);
                    break;
                }
            }
        }

        if (!$nextPrayer) {
            $nextPrayer = 'Tidak ada sholat berikutnya hari ini.';
            $timeToNextPrayerFormatted = '00:00:00';
        } else {
            $timeToNextPrayerFormatted = Carbon::createFromTimestamp($timeToNextPrayer)->format('H:i:s');
        }

        $params = [
            'jadwal' => $jadwal,
            'locations' => $locations,
            'selectedLocationName' => $selectedLocationName,
            'currentTime' => $currentTime,
            'nextPrayer' => $nextPrayer,
            'timeToNextPrayerFormatted' => $timeToNextPrayerFormatted,
        ];

        return view('pages.jadwal-shalat.index-shalat', $params);
    }

    public function getJadwalShalatAjax(Request $request) {

        // Ambil locationId dari query atau cookie
        $locationId = $request->query('locationId', $request->cookie('selectedLocation'));

        // Ambil semua lokasi
        $locations = $this->getLocations();

        // Simpan locationId ke dalam cookie jika ada
        if ($locationId) {
            Cookie::queue('selectedLocation', $locationId, 60 * 24); // Simpan 1 hari
        }

        $selectedLocationName = $locations[$locationId] ?? 'Pilih Lokasi';

        if ($locationId) {
            $response = Http::get("https://jadwalsholat.org/adzan/ajax/next/ajax.daily.php?id={$locationId}");
            $data = $response->json();

            $jadwal = [
                'shubuh' => $data['schedules']['shubuh'] ?? 'N/A',
                'dzuhur' => $data['schedules']['dzuhur'] ?? 'N/A',
                'ashar'  => $data['schedules']['ashr'] ?? 'N/A',
                'maghrib'=> $data['schedules']['maghrib'] ?? 'N/A',
                'isya'   => $data['schedules']['isya'] ?? 'N/A',
            ];
        } else {
            $jadwal = [
                'shubuh' => 'N/A',
                'dzuhur' => 'N/A',
                'ashar'  => 'N/A',
                'maghrib'=> 'N/A',
                'isya'   => 'N/A',
            ];
        }

        $currentTime = Carbon::now();

        $nextPrayer = null;
        $timeToNextPrayer = null;

        foreach ($jadwal as $prayer => $time) {
            if ($time !== 'N/A') {
                $prayerTime = Carbon::parse($time);

                // Jika waktu sholat lebih besar dari waktu saat ini
                if ($prayerTime->isFuture()) {
                    $nextPrayer = $prayer;
                    $timeToNextPrayer = $currentTime->diffInSeconds($prayerTime);
                    break;
                }
            }
        }

        if (!$nextPrayer) {
            $nextPrayer = 'Tidak ada sholat berikutnya hari ini.';
            $timeToNextPrayerFormatted = '00:00:00';
        } else {
            $timeToNextPrayerFormatted = Carbon::createFromTimestamp($timeToNextPrayer)->format('H:i:s');
        }

        return response()->json([
            'jadwal' => $jadwal,
            'selectedLocationName' => $selectedLocationName,
            'currentTime' => $currentTime->format('H:i:s'),
            'nextPrayer' => $nextPrayer,
            'timeToNextPrayerFormatted' => $timeToNextPrayerFormatted,
        ]);
    }


    public function getLocation() {

        $url = 'https://jadwalsholat.org/adzan/ajax.row.php'; // Ganti dengan URL yang relevan

        // Ambil konten HTML dari URL
        $response = Http::get($url);
        $html = $response->body();

        // Buat instance Crawler
        $crawler = new Crawler($html);

        // Ambil data lokasi
        $options = $crawler->filter('select#town-select option')->each(function ($node) {
            $id = $node->attr('value');
            $name = trim($node->text());
            return [
                'id' => $id,
                'name' => $name,
            ];
        });

        // Convert array ke associative array
        $locationsArray = [];
        foreach ($options as $option) {
            $locationsArray[$option['id']] = $option['name'];
        }

        // Kirim data ke view
        return view('pages.jadwal-shalat.index-lokasi', ['locations' => $locationsArray]);
    }

    private function getLocations()
    {
        return [
            '317' => 'Aceh Barat',
            '318' => 'Aceh Barat Daya',
            '319' => 'Aceh Besar',
            '320' => 'Aceh Jaya',
            '321' => 'Aceh Selatan',
            '322' => 'Aceh Singkil',
            '323' => 'Aceh Tamiang',
            '324' => 'Aceh Tengah',
            '325' => 'Aceh Tenggara',
            '326' => 'Aceh Timur',
            '327' => 'Aceh Utara',
            '329' => 'Agam',
            '330' => 'Alor',
            '1' => 'Ambarawa',
            '2' => 'Ambon',
            '3' => 'Amlapura',
            '4' => 'Amuntai',
            '5' => 'Argamakmur',
            '331' => 'Asahan',
            '332' => 'Asmat',
            '6' => 'Atambua',
            '7' => 'Babo',
            '333' => 'Badung',
            '8' => 'Bagan Siapiapi',
            '316' => 'Bahaur, Kalteng',
            '9' => 'Bajawa',
            '334' => 'Balangan',
            '10' => 'Balige',
            '11' => 'Balikpapan',
            '12' => 'Banda Aceh',
            '335' => 'Bandar Lampung',
            '13' => 'Bandarlampung',
            '14' => 'Bandung',
            '336' => 'Bandung Barat',
            '337' => 'Banggai',
            '338' => 'Banggai Kepulauan',
            '339' => 'Banggai Laut',
            '340' => 'Bangka',
            '341' => 'Bangka Barat',
            '342' => 'Bangka Selatan',
            '343' => 'Bangka Tengah',
            '15' => 'Bangkalan',
            '16' => 'Bangkinang',
            '17' => 'Bangko',
            '18' => 'Bangli',
            '19' => 'Banjar',
            '20' => 'Banjar Baru',
            '344' => 'Banjarbaru',
            '21' => 'Banjarmasin',
            '22' => 'Banjarnegara',
            '23' => 'Bantaeng',
            '24' => 'Banten',
            '25' => 'Bantul',
            '345' => 'Banyuasin',
            '346' => 'Banyumas',
            '26' => 'Banyuwangi',
            '27' => 'Barabai',
            '28' => 'Barito',
            '347' => 'Barito Kuala',
            '348' => 'Barito Selatan',
            '349' => 'Barito Timur',
            '350' => 'Barito Utara',
            '29' => 'Barru',
            '30' => 'Batam',
            '31' => 'Batang',
            '351' => 'Batanghari',
            '32' => 'Batu',
            '352' => 'Batu Bara',
            '33' => 'Baturaja',
            '34' => 'Batusangkar',
            '353' => 'Bau Bau',
            '35' => 'Baubau',
            '36' => 'Bekasi',
            '354' => 'Belitung',
            '355' => 'Belitung Timur',
            '356' => 'Belu',
            '357' => 'Bener Meriah',
            '37' => 'Bengkalis',
            '358' => 'Bengkayang',
            '38' => 'Bengkulu',
            '359' => 'Bengkulu Selatan',
            '360' => 'Bengkulu Tengah',
            '361' => 'Bengkulu Utara',
            '39' => 'Benteng',
            '362' => 'Berau',
            '40' => 'Biak',
            '363' => 'Biak Numfor',
            '41' => 'Bima',
            '42' => 'Binjai',
            '364' => 'Bintan',
            '43' => 'Bireuen',
            '44' => 'Bitung',
            '45' => 'Blitar',
            '46' => 'Blora',
            '365' => 'Boalemo',
            '47' => 'Bogor',
            '48' => 'Bojonegoro',
            '366' => 'Bolaang Mongondow',
            '367' => 'Bolaang Mongondow Selatan',
            '368' => 'Bolaang Mongondow Timur',
            '369' => 'Bolaang Mongondow Utara',
            '370' => 'Bombana',
            '49' => 'Bondowoso',
            '371' => 'Bone',
            '372' => 'Bone Bolango',
            '50' => 'Bontang',
            '373' => 'Boven Digoel',
            '51' => 'Boyolali',
            '52' => 'Brebes',
            '53' => 'Bukit Tinggi',
            '374' => 'Bukittinggi',
            '315' => 'Bula SBT, Maluku',
            '375' => 'Buleleng',
            '54' => 'Bulukumba',
            '376' => 'Bulungan',
            '377' => 'Bungo',
            '55' => 'Buntok',
            '378' => 'Buol',
            '379' => 'Buru',
            '380' => 'Buru Selatan',
            '381' => 'Buton',
            '382' => 'Buton Selatan',
            '383' => 'Buton Tengah',
            '384' => 'Buton Utara',
            '56' => 'Cepu',
            '57' => 'Ciamis',
            '58' => 'Cianjur',
            '59' => 'Cibinong',
            '60' => 'Cilacap',
            '61' => 'Cilegon',
            '62' => 'Cimahi',
            '63' => 'Cirebon',
            '64' => 'Curup',
            '385' => 'Dairi',
            '386' => 'Deiyai',
            '387' => 'Deli Serdang',
            '65' => 'Demak',
            '66' => 'Denpasar',
            '67' => 'Depok',
            '388' => 'Dharmasraya',
            '68' => 'Dili',
            '389' => 'Dogiyai',
            '69' => 'Dompu',
            '70' => 'Donggala',
            '71' => 'Dumai',
            '390' => 'Empat Lawang',
            '72' => 'Ende',
            '73' => 'Enggano',
            '74' => 'Enrekang',
            '391' => 'Fak Fak',
            '75' => 'Fakfak',
            '392' => 'Flores Timur',
            '76' => 'Garut',
            '393' => 'Gayo Lues',
            '77' => 'Gianyar',
            '78' => 'Gombong',
            '79' => 'Gorontalo',
            '394' => 'Gorontalo Utara',
            '395' => 'Gowa',
            '80' => 'Gresik',
            '396' => 'Grobogan',
            '397' => 'Gunung Mas',
            '81' => 'Gunung Sitoli',
            '398' => 'Gunungkidul',
            '399' => 'Gunungsitoli',
            '400' => 'Halmahera Barat',
            '401' => 'Halmahera Selatan',
            '402' => 'Halmahera Tengah',
            '403' => 'Halmahera Timur',
            '404' => 'Halmahera Utara',
            '405' => 'Hulu Sungai Selatan',
            '406' => 'Hulu Sungai Tengah',
            '407' => 'Hulu Sungai Utara',
            '408' => 'Humbang Hasundutan',
            '409' => 'Indragiri Hilir',
            '410' => 'Indragiri Hulu',
            '82' => 'Indramayu',
            '411' => 'Intan Jaya',
            '309' => 'Jakarta Barat',
            '308' => 'Jakarta Pusat',
            '310' => 'Jakarta Selatan',
            '311' => 'Jakarta Timur',
            '312' => 'Jakarta Utara',
            '83' => 'Jambi',
            '84' => 'Jayapura',
            '412' => 'Jayawijaya',
            '85' => 'Jember',
            '413' => 'Jembrana',
            '86' => 'Jeneponto',
            '87' => 'Jepara',
            '88' => 'Jombang',
            '414' => 'Kab Timor Tengah Selatan',
            '89' => 'Kabanjahe',
            '415' => 'Kaimana',
            '90' => 'Kalabahi',
            '91' => 'Kalianda',
            '416' => 'Kampar',
            '92' => 'Kandangan',
            '417' => 'Kapuas',
            '418' => 'Kapuas Hulu',
            '93' => 'Karanganyar',
            '419' => 'Karangasem',
            '94' => 'Karawang',
            '420' => 'Karimun',
            '421' => 'Karo',
            '95' => 'Kasungan',
            '422' => 'Katingan',
            '423' => 'Kaur',
            '424' => 'Kayong Utara',
            '96' => 'Kayuagung',
            '97' => 'Kebumen',
            '98' => 'Kediri',
            '425' => 'Keerom',
            '99' => 'Kefamenanu',
            '100' => 'Kendal',
            '101' => 'Kendari',
            '328' => 'Kep. Seribu',
            '426' => 'Kep. Siau Tagulandang Biaro',
            '427' => 'Kepahiang',
            '428' => 'Kepulauan Anambas',
            '429' => 'Kepulauan Aru',
            '430' => 'Kepulauan Mentawai',
            '431' => 'Kepulauan Meranti',
            '432' => 'Kepulauan Sangihe',
            '433' => 'Kepulauan Selayar',
            '434' => 'Kepulauan Sula',
            '435' => 'Kepulauan Talaud',
            '436' => 'Kepulauan Tanimbar',
            '437' => 'Kepulauan Yapen',
            '438' => 'Kerinci',
            '102' => 'Kertosono',
            '103' => 'Ketapang',
            '104' => 'Kisaran',
            '105' => 'Klaten',
            '439' => 'Klungkung',
            '106' => 'Kolaka',
            '440' => 'Kolaka Timur',
            '441' => 'Kolaka Utara',
            '442' => 'Konawe',
            '443' => 'Konawe Kepulauan',
            '444' => 'Konawe Selatan',
            '445' => 'Konawe Utara',
            '107' => 'Kota Baru Pulau Laut',
            '108' => 'Kota Bumi',
            '109' => 'Kota Jantho',
            '446' => 'Kotabaru',
            '110' => 'Kotamobagu',
            '447' => 'Kotawaringin Barat',
            '448' => 'Kotawaringin Timur',
            '111' => 'Kuala Kapuas',
            '112' => 'Kuala Kurun',
            '113' => 'Kuala Pembuang',
            '114' => 'Kuala Tungkal',
            '449' => 'Kuantan Singingi',
            '450' => 'Kubu Raya',
            '115' => 'Kudus',
            '451' => 'Kulon Progo',
            '116' => 'Kuningan',
            '117' => 'Kupang',
            '118' => 'Kutacane',
            '452' => 'Kutai Barat',
            '453' => 'Kutai Kartanegara',
            '454' => 'Kutai Timur',
            '119' => 'Kutoarjo',
            '120' => 'Labuhan',
            '455' => 'Labuhan Batu',
            '456' => 'Labuhan Batu Selatan',
            '457' => 'Labuhan Batu Utara',
            '121' => 'Lahat',
            '458' => 'Lamandau',
            '122' => 'Lamongan',
            '459' => 'Lampung Barat',
            '460' => 'Lampung Selatan',
            '461' => 'Lampung Tengah',
            '462' => 'Lampung Timur',
            '463' => 'Lampung Utara',
            '464' => 'Landak',
            '465' => 'Langkat',
            '123' => 'Langsa',
            '466' => 'Lanny Jaya',
            '124' => 'Larantuka',
            '125' => 'Lawang',
            '467' => 'Lebak',
            '468' => 'Lebong',
            '469' => 'Lembata',
            '470' => 'Lhokseumawe',
            '126' => 'Lhoseumawe',
            '471' => 'Lima Puluh Kota',
            '127' => 'Limboto',
            '472' => 'Lingga',
            '473' => 'Lombok Barat',
            '474' => 'Lombok Tengah',
            '475' => 'Lombok Timur',
            '476' => 'Lombok Utara',
            '128' => 'Lubuk Basung',
            '129' => 'Lubuk Linggau',
            '130' => 'Lubuk Pakam',
            '131' => 'Lubuk Sikaping',
            '132' => 'Lumajang',
            '477' => 'Luwu',
            '478' => 'Luwu Timur',
            '479' => 'Luwu Utara',
            '133' => 'Luwuk',
            '134' => 'Madiun',
            '135' => 'Magelang',
            '136' => 'Magetan',
            '480' => 'Mahakam Ulu',
            '137' => 'Majalengka',
            '138' => 'Majene',
            '139' => 'Makale',
            '140' => 'Makassar',
            '481' => 'Malaka',
            '141' => 'Malang',
            '482' => 'Malinau',
            '483' => 'Maluku Barat Daya',
            '484' => 'Maluku Tengah',
            '485' => 'Maluku Tenggara',
            '486' => 'Mamasa',
            '487' => 'Mamberamo Raya',
            '488' => 'Mamberamo Tengah',
            '142' => 'Mamuju',
            '489' => 'Mamuju Tengah',
            '490' => 'Manado',
            '491' => 'Mandailing Natal',
            '492' => 'Manggarai',
            '493' => 'Manggarai Barat',
            '494' => 'Manggarai Timur',
            '143' => 'Manna',
            '144' => 'Manokwari',
            '495' => 'Manokwari Selatan',
            '496' => 'Mappi',
            '145' => 'Marabahan',
            '146' => 'Maros',
            '147' => 'Martapura Kalsel',
            '314' => 'Masamba, Sulsel',
            '148' => 'Masohi',
            '149' => 'Mataram',
            '150' => 'Maumere',
            '497' => 'Maybrat',
            '151' => 'Medan',
            '498' => 'Melawi',
            '152' => 'Mempawah',
            '153' => 'Menado',
            '154' => 'Mentok',
            '499' => 'Merangin',
            '155' => 'Merauke',
            '500' => 'Mesuji',
            '156' => 'Metro',
            '157' => 'Meulaboh',
            '501' => 'Mimika',
            '502' => 'Minahasa',
            '503' => 'Minahasa Selatan',
            '504' => 'Minahasa Tenggara',
            '505' => 'Minahasa Utara',
            '158' => 'Mojokerto',
            '506' => 'Morowali',
            '507' => 'Morowali Utara',
            '159' => 'Muara Bulian',
            '160' => 'Muara Bungo',
            '161' => 'Muara Enim',
            '162' => 'Muara Teweh',
            '508' => 'Muaro Jambi',
            '163' => 'Muaro Sijunjung',
            '509' => 'Muko Muko',
            '510' => 'Muna',
            '511' => 'Muna Barat',
            '164' => 'Muntilan',
            '512' => 'Murung Raya',
            '513' => 'Musi Banyuasin',
            '514' => 'Musi Rawas',
            '515' => 'Musi Rawas Utara',
            '165' => 'Nabire',
            '516' => 'Nagan Raya',
            '517' => 'Nagekeo',
            '518' => 'Natuna',
            '519' => 'Nduga',
            '166' => 'Negara',
            '520' => 'Ngada',
            '167' => 'Nganjuk',
            '168' => 'Ngawi',
            '521' => 'Nias',
            '522' => 'Nias Barat',
            '523' => 'Nias Selatan',
            '524' => 'Nias Utara',
            '169' => 'Nunukan',
            '525' => 'Ogan Ilir',
            '526' => 'Ogan Komering Ilir',
            '527' => 'Ogan Komering Ulu',
            '528' => 'Ogan Komering Ulu Selatan',
            '529' => 'Ogan Komering Ulu Timur',
            '170' => 'Pacitan',
            '171' => 'Padang',
            '530' => 'Padang Lawas',
            '531' => 'Padang Lawas Utara',
            '172' => 'Padang Panjang',
            '532' => 'Padang Pariaman',
            '173' => 'Padang Sidempuan',
            '533' => 'Padangsidimpuan',
            '534' => 'Pagar Alam',
            '174' => 'Pagaralam',
            '535' => 'Pahuwato',
            '175' => 'Painan',
            '536' => 'Pakpak Bharat',
            '176' => 'Palangkaraya',
            '177' => 'Palembang',
            '178' => 'Palopo',
            '179' => 'Palu',
            '180' => 'Pamekasan',
            '181' => 'Pandeglang',
            '537' => 'Pangandaran',
            '182' => 'Pangkajene',
            '538' => 'Pangkajene Kepulauan',
            '183' => 'Pangkajene Sidenreng',
            '539' => 'Pangkal Pinang',
            '184' => 'Pangkalan Bun',
            '185' => 'Pangkalpinang',
            '540' => 'Paniai',
            '186' => 'Panyabungan',
            '187' => 'Pare',
            '188' => 'Parepare',
            '189' => 'Pariaman',
            '541' => 'Parigi Moutong',
            '542' => 'Pasaman',
            '543' => 'Pasaman Barat',
            '544' => 'Pasangkayu',
            '545' => 'Paser',
            '190' => 'Pasuruan',
            '191' => 'Pati',
            '192' => 'Payakumbuh',
            '546' => 'Pegunungan Arfak',
            '547' => 'Pegunungan Bintang',
            '193' => 'Pekalongan',
            '194' => 'Pekan Baru',
            '548' => 'Pekanbaru',
            '549' => 'Pelalawan',
            '195' => 'Pemalang',
            '196' => 'Pematangsiantar',
            '550' => 'Penajam Paser Utara',
            '197' => 'Pendopo',
            '551' => 'Penukal Abab Lematang Ilir',
            '552' => 'Pesawaran',
            '553' => 'Pesisir Barat',
            '554' => 'Pesisir Selatan',
            '555' => 'Pidie',
            '556' => 'Pidie Jaya',
            '198' => 'Pinrang',
            '199' => 'Pleihari',
            '200' => 'Polewali',
            '557' => 'Polewali Mandar',
            '201' => 'Pondok Gede',
            '202' => 'Ponorogo',
            '203' => 'Pontianak',
            '204' => 'Poso',
            '205' => 'Prabumulih',
            '206' => 'Praya',
            '558' => 'Pringsewu',
            '207' => 'Probolinggo',
            '559' => 'Pulang Pisau',
            '560' => 'Pulau Morotai',
            '561' => 'Pulau Taliabu',
            '562' => 'Puncak',
            '563' => 'Puncak Jaya',
            '208' => 'Purbalingga',
            '209' => 'Purukcahu',
            '210' => 'Purwakarta',
            '211' => 'Purwodadigrobogan',
            '212' => 'Purwokerto',
            '213' => 'Purworejo',
            '214' => 'Putussibau',
            '215' => 'Raha',
            '564' => 'Raja Ampat',
            '216' => 'Rangkasbitung',
            '217' => 'Rantau',
            '218' => 'Rantauprapat',
            '219' => 'Rantepao',
            '565' => 'Rejang Lebong',
            '220' => 'Rembang',
            '221' => 'Rengat',
            '566' => 'Rokan Hilir',
            '567' => 'Rokan Hulu',
            '568' => 'Rote Ndao',
            '222' => 'Ruteng',
            '223' => 'Sabang',
            '569' => 'Sabu Raijua',
            '224' => 'Salatiga',
            '225' => 'Samarinda',
            '570' => 'Sambas',
            '313' => 'Sambas, Kalbar',
            '571' => 'Samosir',
            '226' => 'Sampang',
            '227' => 'Sampit',
            '228' => 'Sanggau',
            '572' => 'Sarmi',
            '573' => 'Sarolangun',
            '229' => 'Sawahlunto',
            '574' => 'Sekadau',
            '230' => 'Sekayu',
            '231' => 'Selong',
            '575' => 'Seluma',
            '232' => 'Semarang',
            '233' => 'Sengkang',
            '576' => 'Seram Bagian Barat',
            '577' => 'Seram Bagian Timur',
            '234' => 'Serang',
            '578' => 'Serdang Bedagai',
            '235' => 'Serui',
            '579' => 'Seruyan',
            '580' => 'Siak',
            '236' => 'Sibolga',
            '581' => 'Sidenreng Rappang',
            '237' => 'Sidikalang',
            '238' => 'Sidoarjo',
            '582' => 'Sigi',
            '239' => 'Sigli',
            '583' => 'Sijunjung',
            '584' => 'Sikka',
            '585' => 'Simalungun',
            '586' => 'Simeulue',
            '240' => 'Singaparna',
            '241' => 'Singaraja',
            '242' => 'Singkawang',
            '243' => 'Sinjai',
            '244' => 'Sintang',
            '245' => 'Situbondo',
            '246' => 'Slawi',
            '247' => 'Sleman',
            '248' => 'Soasiu',
            '249' => 'Soe',
            '250' => 'Solo',
            '251' => 'Solok',
            '587' => 'Solok Selatan',
            '588' => 'Soppeng',
            '252' => 'Soreang',
            '253' => 'Sorong',
            '589' => 'Sorong Selatan',
            '254' => 'Sragen',
            '255' => 'Stabat',
            '256' => 'Subang',
            '590' => 'Subulussalam',
            '257' => 'Sukabumi',
            '591' => 'Sukamara',
            '258' => 'Sukoharjo',
            '592' => 'Sumba Barat',
            '593' => 'Sumba Barat Daya',
            '594' => 'Sumba Tengah',
            '595' => 'Sumba Timur',
            '596' => 'Sumbawa',
            '597' => 'Sumbawa Barat',
            '259' => 'Sumbawa Besar',
            '260' => 'Sumedang',
            '261' => 'Sumenep',
            '262' => 'Sungai Liat',
            '263' => 'Sungai Penuh',
            '264' => 'Sungguminasa',
            '598' => 'Supiori',
            '265' => 'Surabaya',
            '266' => 'Surakarta',
            '599' => 'Tabalong',
            '267' => 'Tabanan',
            '268' => 'Tahuna',
            '269' => 'Takalar',
            '270' => 'Takengon',
            '600' => 'Tambrauw',
            '271' => 'Tamiang Layang',
            '601' => 'Tana Tidung',
            '602' => 'Tana Toraja',
            '603' => 'Tanah Bumbu',
            '604' => 'Tanah Datar',
            '272' => 'Tanah Grogot',
            '605' => 'Tanah Laut',
            '273' => 'Tangerang',
            '606' => 'Tangerang Selatan',
            '607' => 'Tanggamus',
            '274' => 'Tanjung Balai',
            '275' => 'Tanjung Enim',
            '608' => 'Tanjung Jabung Barat',
            '609' => 'Tanjung Jabung Timur',
            '276' => 'Tanjung Pandan',
            '277' => 'Tanjung Pinang',
            '278' => 'Tanjung Redep',
            '279' => 'Tanjung Selor',
            '280' => 'Tapak Tuan',
            '610' => 'Tapanuli Selatan',
            '611' => 'Tapanuli Tengah',
            '612' => 'Tapanuli Utara',
            '613' => 'Tapin',
            '281' => 'Tarakan',
            '282' => 'Tarutung',
            '283' => 'Tasikmalaya',
            '284' => 'Tebing Tinggi',
            '614' => 'Tebo',
            '285' => 'Tegal',
            '615' => 'Teluk Bintuni',
            '616' => 'Teluk Wondama',
            '286' => 'Temanggung',
            '287' => 'Tembilahan',
            '288' => 'Tenggarong',
            '289' => 'Ternate',
            '617' => 'Tidore Kepulauan',
            '618' => 'Timor Tengah Utara',
            '619' => 'Toba',
            '620' => 'Tojo Una Una',
            '621' => 'Toli Toli',
            '622' => 'Tolikara',
            '290' => 'Tolitoli',
            '623' => 'Tomohon',
            '291' => 'Tondano',
            '624' => 'Toraja Utara',
            '292' => 'Trenggalek',
            '293' => 'Tual',
            '294' => 'Tuban',
            '625' => 'Tulang Bawang',
            '626' => 'Tulang Bawang Barat',
            '295' => 'Tulung Agung',
            '627' => 'Tulungagung',
            '296' => 'Ujung Berung',
            '297' => 'Ungaran',
            '298' => 'Waikabubak',
            '299' => 'Waingapu',
            '628' => 'Wajo',
            '629' => 'Wakatobi',
            '300' => 'Wamena',
            '630' => 'Waropen',
            '301' => 'Watampone',
            '302' => 'Watansoppeng',
            '303' => 'Wates',
            '631' => 'Way Kanan',
            '304' => 'Wonogiri',
            '305' => 'Wonosari',
            '306' => 'Wonosobo',
            '632' => 'Yahukimo',
            '633' => 'Yalimo',
            '307' => 'Yogyakarta',
        ];
    }

}
